"""remove extend existing for game_user table

Revision ID: 6f0b2627ff91
Revises: a2ee6ee78cca
Create Date: 2023-08-06 11:06:14.356389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0b2627ff91'
down_revision = 'a2ee6ee78cca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
