"""add onDelete=CASCADE for ForeignKey in game_user table

Revision ID: 78a39cec99b1
Revises: 6f0b2627ff91
Create Date: 2023-08-06 12:34:31.968031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a39cec99b1'
down_revision = '6f0b2627ff91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_game_users_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_game_users_game_id_games', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_game_users_game_id_games'), 'games', ['game_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_game_users_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_game_users_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_game_users_game_id_games'), type_='foreignkey')
        batch_op.create_foreign_key('fk_game_users_game_id_games', 'games', ['game_id'], ['id'])
        batch_op.create_foreign_key('fk_game_users_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
